Repository ORNL/ReSolve, pull requests merged in 2023-12, with the labels that each got.

#74 bugifx: only test on ascent after module rebuild
  .gitlab-ci.yml
Labels: bug, testing

#83 Randomized solver (both cuda and hip)
  CMakePresets.json
  examples/CMakeLists.txt
  examples/r_randGMRES.cpp
  examples/r_randGMRES_CUDA.cpp
  resolve/CMakeLists.txt
  resolve/GramSchmidt.cpp
  resolve/GramSchmidt.hpp
  resolve/LinSolverDirectCuSparseILU0.cpp
  resolve/LinSolverDirectCuSparseILU0.hpp
  resolve/LinSolverDirectRocSparseILU0.cpp
  resolve/LinSolverDirectRocSparseILU0.hpp
  resolve/LinSolverIterativeFGMRES.cpp
  resolve/LinSolverIterativeFGMRES.hpp
  resolve/LinSolverIterativeRandFGMRES.cpp
  resolve/LinSolverIterativeRandFGMRES.hpp
  resolve/RandSketchingCountSketch.cpp
  resolve/RandSketchingCountSketch.hpp
  resolve/RandSketchingFWHT.cpp
  resolve/RandSketchingFWHT.hpp
  resolve/RandSketchingManager.cpp
  resolve/RandSketchingManager.hpp
  resolve/cuda/cudaKernels.cu
  resolve/cuda/cudaKernels.h
  resolve/hip/hipKernels.h
  resolve/hip/hipKernels.hip
  resolve/vector/VectorHandlerHip.cpp
  tests/functionality/CMakeLists.txt
  tests/functionality/testRandGMRES_Cuda.cpp
  tests/functionality/testRandGMRES_Rocm.cpp
Labels: enhancement

#100 Create Csr constructor that takes Coo as the argument
  examples/r_KLU_GLU.cpp
  examples/r_KLU_GLU_matrix_values_update.cpp
  examples/r_KLU_KLU.cpp
  examples/r_KLU_KLU_standalone.cpp
  examples/r_KLU_rf.cpp
  examples/r_KLU_rf_FGMRES.cpp
  examples/r_KLU_rf_FGMRES_reuse_factorization.cpp
  examples/r_KLU_rocSolverRf_FGMRES.cpp
  examples/r_KLU_rocsolverrf.cpp
  examples/r_KLU_rocsolverrf_redo_factorization.cpp
  examples/r_SysSolver.cpp
  examples/r_SysSolverCuda.cpp
  examples/r_SysSolverHip.cpp
  examples/r_SysSolverHipRefine.cpp
  examples/r_randGMRES.cpp
  examples/r_randGMRES_CUDA.cpp
  resolve/matrix/Csr.cpp
  resolve/matrix/Csr.hpp
  tests/functionality/testKLU.cpp
  tests/functionality/testKLU_GLU.cpp
  tests/functionality/testKLU_Rf.cpp
  tests/functionality/testKLU_Rf_FGMRES.cpp
  tests/functionality/testKLU_RocSolver.cpp
  tests/functionality/testKLU_RocSolver_FGMRES.cpp
  tests/functionality/testSysCuda.cpp
  tests/functionality/testSysHipRefine.cpp
Labels: enhancement

#108 Doxygen updates dev
  CMakeLists.txt
  LICENSE
  NOTICE
  cmake/ReSolveFindDoxygen.cmake
  docs/doxygen/Doxyfile.in
  docs/doxygen/doxygen-awesome-darkmode-toggle.js
  docs/doxygen/doxygen-awesome-fragment-copy-button.js
  docs/doxygen/doxygen-awesome-interactive-toc.js
  docs/doxygen/doxygen-awesome-paragraph-link.js
  docs/doxygen/doxygen-awesome-tabs.js
  docs/sphinx/notice.rst
  resolve/Doxygen.hpp
Labels: documentation, enhancement

#107 Protect GPU kernels with appropriate nemespaces.
  resolve/cuda/CMakeLists.txt
  resolve/cuda/VectorKernels.cu
  resolve/cuda/cudaKernels.cu
  resolve/cuda/cudaKernels.h
  resolve/cuda/cudaVectorKernels.cu
  resolve/cuda/cudaVectorKernels.h
  resolve/hip/CMakeLists.txt
  resolve/hip/VectorKernels.hip
  resolve/hip/hipKernels.h
  resolve/hip/hipKernels.hip
  resolve/hip/hipVectorKernels.h
  resolve/vector/VectorKernels.hpp
Labels: documentation, enhancement, hip, cuda

#109 fixing failing test
  resolve/LinSolverIterativeFGMRES.cpp
  tests/functionality/testKLU_Rf_FGMRES.cpp
Labels: bug, testing, cuda

#110 Refactor handlers
  examples/r_KLU_GLU.cpp
  examples/r_KLU_GLU_matrix_values_update.cpp
  examples/r_KLU_KLU.cpp
  examples/r_KLU_KLU_standalone.cpp
  examples/r_KLU_cusolverrf_redo_factorization.cpp
  examples/r_KLU_rf.cpp
  examples/r_KLU_rf_FGMRES.cpp
  examples/r_KLU_rf_FGMRES_reuse_factorization.cpp
  examples/r_KLU_rocSolverRf_FGMRES.cpp
  examples/r_KLU_rocsolverrf.cpp
  examples/r_KLU_rocsolverrf_redo_factorization.cpp
  examples/r_SysSolver.cpp
  examples/r_randGMRES.cpp
  examples/r_randGMRES_CUDA.cpp
  resolve/GramSchmidt.cpp
  resolve/GramSchmidt.hpp
  resolve/LinSolverIterativeFGMRES.cpp
  resolve/LinSolverIterativeFGMRES.hpp
  resolve/LinSolverIterativeRandFGMRES.cpp
  resolve/LinSolverIterativeRandFGMRES.hpp
  resolve/SystemSolver.cpp
  resolve/matrix/MatrixHandler.cpp
  resolve/matrix/MatrixHandler.hpp
  resolve/matrix/MatrixHandlerCuda.cpp
  resolve/matrix/MatrixHandlerHip.cpp
  resolve/vector/VectorHandler.cpp
  resolve/vector/VectorHandler.hpp
  resolve/vector/VectorHandlerCpu.cpp
  resolve/vector/VectorHandlerCpu.hpp
  resolve/vector/VectorHandlerCuda.cpp
  resolve/vector/VectorHandlerCuda.hpp
  resolve/vector/VectorHandlerHip.cpp
  resolve/vector/VectorHandlerHip.hpp
  resolve/vector/VectorHandlerImpl.hpp
  tests/functionality/testKLU.cpp
  tests/functionality/testKLU_GLU.cpp
  tests/functionality/testKLU_Rf.cpp
  tests/functionality/testKLU_Rf_FGMRES.cpp
  tests/functionality/testKLU_RocSolver.cpp
  tests/functionality/testKLU_RocSolver_FGMRES.cpp
  tests/functionality/testRandGMRES_Cuda.cpp
  tests/functionality/testRandGMRES_Rocm.cpp
  tests/functionality/testSysCuda.cpp
  tests/functionality/testSysHipRefine.cpp
  tests/unit/matrix/MatrixHandlerTests.hpp
  tests/unit/vector/GramSchmidtTests.hpp
  tests/unit/vector/VectorHandlerTests.hpp
Labels: enhancement, hip, cuda

#111 SDK compliance of adding api version
  CMakeLists.txt
  resolve/CMakeLists.txt
  resolve/SystemSolver.cpp
  resolve/resolve_defs.hpp.in
  resolve/utilities/CMakeLists.txt
  resolve/utilities/version/CMakeLists.txt
  resolve/utilities/version/version.cpp
  resolve/utilities/version/version.hpp
  tests/functionality/CMakeLists.txt
  tests/functionality/testVersion.cpp
Labels: xSDK

#117 Build without KLU, first stab.
  examples/CMakeLists.txt
  resolve/CMakeLists.txt
  resolve/SystemSolver.cpp
  tests/functionality/CMakeLists.txt
Labels: testing, cmake

#125 Use memspace as parameter consistently in FGMRES classes.
  resolve/GramSchmidt.cpp
  resolve/LinSolverDirectRocSparseILU0.hpp
  resolve/LinSolverIterativeFGMRES.cpp
  resolve/LinSolverIterativeFGMRES.hpp
  resolve/LinSolverIterativeRandFGMRES.cpp
  resolve/LinSolverIterativeRandFGMRES.hpp
Labels: enhancement, hip, cuda

#124 Fix bug when data/values ownership is incorrectly assigned.
  resolve/matrix/Coo.cpp
  resolve/matrix/Csc.cpp
  resolve/matrix/Csr.cpp
  resolve/matrix/Sparse.cpp
  resolve/vector/Vector.cpp
  resolve/vector/VectorHandlerCuda.cpp
  tests/functionality/testKLU_GLU.cpp
  tests/functionality/testKLU_RocSolver_FGMRES.cpp
Labels: bug

#103 Ascent build system based on LLVM clang
  CMakeLists.txt
  CMakePresets.json
  buildsystem/ascent-clang-env.sh
  buildsystem/build.sh
Labels: enhancement, cmake

#120 SystemSolver Interface updates
  CMakePresets.json
  examples/r_KLU_rocSolverRf_FGMRES.cpp
  examples/r_SysSolverHipRefine.cpp
  examples/r_randGMRES.cpp
  examples/r_randGMRES_CUDA.cpp
  resolve/GramSchmidt.cpp
  resolve/GramSchmidt.hpp
  resolve/LinSolverDirectCuSolverRf.cpp
  resolve/LinSolverDirectCuSolverRf.hpp
  resolve/LinSolverDirectRocSolverRf.hpp
  resolve/LinSolverDirectRocSparseILU0.hpp
  resolve/LinSolverIterativeFGMRES.cpp
  resolve/LinSolverIterativeFGMRES.hpp
  resolve/LinSolverIterativeRandFGMRES.cpp
  resolve/LinSolverIterativeRandFGMRES.hpp
  resolve/SystemSolver.cpp
  resolve/SystemSolver.hpp
  resolve/matrix/Coo.cpp
  resolve/matrix/Csc.cpp
  resolve/matrix/Csr.cpp
  resolve/matrix/MatrixHandler.cpp
  resolve/matrix/MatrixHandler.hpp
  resolve/matrix/Sparse.cpp
  resolve/vector/Vector.cpp
  resolve/vector/VectorHandler.cpp
  resolve/vector/VectorHandler.hpp
  resolve/vector/VectorHandlerCuda.cpp
  tests/functionality/CMakeLists.txt
  tests/functionality/testKLU.cpp
  tests/functionality/testKLU_GLU.cpp
  tests/functionality/testKLU_Rf.cpp
  tests/functionality/testKLU_Rf_FGMRES.cpp
  tests/functionality/testKLU_RocSolver.cpp
  tests/functionality/testKLU_RocSolver_FGMRES.cpp
  tests/functionality/testRandGMRES_Cuda.cpp
  tests/functionality/testRandGMRES_Rocm.cpp
  tests/functionality/testSysCuda.cpp
  tests/functionality/testSysGLU.cpp
  tests/functionality/testSysHipRefine.cpp
  tests/functionality/testSysRandGMRES.cpp
  tests/functionality/testSysRefactor.cpp
  tests/functionality/testVersion.cpp
  tests/unit/vector/GramSchmidtTests.hpp
Labels: enhancement, hip, cuda

#132 Unit tests for Gram-Schmidt methods on CPU backend
  resolve/GramSchmidt.cpp
  resolve/cuda/cudaKernels.cu
  resolve/hip/hipKernels.hip
  resolve/vector/VectorHandlerCpu.cpp
  resolve/vector/VectorHandlerCuda.cpp
  tests/unit/vector/GramSchmidtTests.hpp
  tests/unit/vector/runGramSchmidtTests.cpp
Labels: testing
