Repository ORNL/ReSolve, pull requests merged in 2023-11, with the labels that each got.

#48 Review CUDA and HIP configuration in CMake
  CMakeLists.txt
  CMakePresets.json
  cmake/ReSolveConfig.cmake.in
  cmake/ReSolveFindHipLibraries.cmake
  resolve/CMakeLists.txt
Labels: enhancement, cmake

#49 Fix segfault in examples
  examples/r_KLU_rf.cpp
  examples/r_KLU_rf_FGMRES.cpp
  examples/r_KLU_rf_FGMRES_reuse_factorization.cpp
Labels: bug, testing

#50 Enable HIP support in Gramm-Schmidt and FGMRES
  examples/CMakeLists.txt
  examples/r_KLU_rf_FGMRES.cpp
  examples/r_KLU_rf_FGMRES_reuse_factorization.cpp
  examples/r_KLU_rocSolverRf_FGMRES.cpp
  resolve/CMakeLists.txt
  resolve/GramSchmidt.cpp
  resolve/LinSolverIterativeFGMRES.cpp
  resolve/LinSolverIterativeFGMRES.hpp
  resolve/vector/Vector.cpp
  tests/functionality/testKLU_Rf_FGMRES.cpp
Labels: enhancement, hip

#56 A working alternative triangular solver (faster) for rocsolverrf
  examples/r_KLU_rocSolverRf_FGMRES.cpp
  resolve/LinSolverDirectRocSolverRf.cpp
  resolve/LinSolverDirectRocSolverRf.hpp
  resolve/hip/hipKernels.h
  resolve/hip/hipKernels.hip
  resolve/hip/hipVectorKernels.hip
Labels: enhancement, hip

#58 Add rocsolver+FGMRES test
  tests/functionality/CMakeLists.txt
  tests/functionality/testKLU_RocSolver_FGMRES.cpp
Labels: enhancement, testing, hip

#62 Fix warnings stemming from rocsolver class
  examples/r_KLU_rocSolverRf_FGMRES.cpp
  examples/r_KLU_rocsolverrf.cpp
  resolve/LinSolver.cpp
  resolve/LinSolver.hpp
  resolve/LinSolverDirectCuSolverGLU.cpp
  resolve/LinSolverDirectCuSolverGLU.hpp
  resolve/LinSolverDirectCuSolverRf.cpp
  resolve/LinSolverDirectCuSolverRf.hpp
  resolve/LinSolverDirectKLU.cpp
  resolve/LinSolverDirectKLU.hpp
  resolve/LinSolverDirectRocSolverRf.cpp
  resolve/LinSolverDirectRocSolverRf.hpp
Labels: hip

#69 Fixing minor leftovers from Frontier hackathon
  resolve/GramSchmidt.cpp
  resolve/hip/hipKernels.hip
  resolve/matrix/MatrixHandler.cpp
  resolve/vector/VectorHandler.cpp
Labels: bug

#70 Corrections to the README file
  NOTICE
  README.md
Labels: documentation

#77 Added example with redoing the factorization through KLU
  examples/CMakeLists.txt
  examples/r_KLU_rocsolverrf_redo_factorization.cpp
  resolve/LinSolverDirectKLU.cpp
  resolve/LinSolverDirectRocSolverRf.cpp
  resolve/LinSolverDirectRocSolverRf.hpp
Labels: bug, enhancement
