Repository ORNL/ReSolve, pull requests merged in 2023-10, with the labels that each got.

#4 Ascent Ci for ReSolve and Github
  .github/pnnl_mirror.yaml
  .github/workflows/.clang-format
  .github/workflows/.cmake-format.py
  .github/workflows/ornl_ascent_mirror.yaml
  .gitlab-ci.yml
Labels: testing

#26 Trying to restore test install
  buildsystem/build.sh
Labels: bug

#34 Fix issue with hard-wired CUDA consumer.
  cmake/ReSolveConfig.cmake.in
  examples/CMakeLists.txt
  examples/resolve_consumer/CMakeLists.txt
Labels: bug, testing

#41 Fix warnings in HIP branch.
  resolve/LinSolverDirectKLU.cpp
  resolve/MemoryUtils.hpp
  resolve/matrix/Coo.cpp
  resolve/matrix/Csc.cpp
  resolve/matrix/Csr.cpp
  resolve/matrix/MatrixHandlerCpu.hpp
  resolve/matrix/Sparse.cpp
  resolve/utilities/logger/Logger.cpp
  resolve/vector/Vector.cpp
  resolve/workspace/LinAlgWorkspaceCpu.cpp
  resolve/workspace/LinAlgWorkspaceCpu.hpp
  resolve/workspace/LinAlgWorkspaceHIP.hpp
  tests/unit/matrix/MatrixHandlerTests.hpp
Labels: bug, hip
