Repository ORNL/ReSolve, pull requests merged in 2024-02, with the labels that each got.

#138 Fix compiler warnings
  resolve/LinSolverDirectSerialILU0.cpp
  resolve/LinSolverIterativeRandFGMRES.cpp
  resolve/RandSketchingFWHT.cpp
  resolve/cpu/cpuKernels.cpp
  tests/unit/vector/GramSchmidtTests.hpp
Labels: bug

#137 add cpu only rand solver to develop branch.
  examples/CMakeLists.txt
  examples/r_SysSolver.cpp
  examples/r_randGMRES_cpu.cpp
  resolve/CMakeLists.txt
  resolve/LinSolverDirectSerialILU0.cpp
  resolve/LinSolverDirectSerialILU0.hpp
  resolve/LinSolverIterativeRandFGMRES.cpp
  resolve/RandSketchingCountSketch.cpp
  resolve/RandSketchingCountSketch.hpp
  resolve/RandSketchingFWHT.cpp
  resolve/RandSketchingFWHT.hpp
  resolve/SystemSolver.cpp
  resolve/SystemSolver.hpp
  resolve/cpu/CMakeLists.txt
  resolve/cpu/cpuKernels.cpp
  resolve/cpu/cpuKernels.h
  tests/functionality/CMakeLists.txt
  tests/functionality/testSysRandGMRES.cpp
  tests/unit/vector/GramSchmidtTests.hpp
Labels: enhancement

#135 Enhancements to Matrix Functions
  .github/workflows/pnnl_mirror.yaml
  resolve/CMakeLists.txt
  resolve/LinSolver.hpp
  resolve/LinSolverDirectCpuILU0.cpp
  resolve/LinSolverDirectCpuILU0.hpp
  resolve/LinSolverDirectRocSparseILU0.cpp
  resolve/LinSolverDirectRocSparseILU0.hpp
  resolve/matrix/Coo.cpp
  resolve/matrix/Coo.hpp
  resolve/matrix/Csc.cpp
  resolve/matrix/Csc.hpp
  resolve/matrix/Csr.cpp
  resolve/matrix/Csr.hpp
  resolve/matrix/Sparse.cpp
  resolve/matrix/Sparse.hpp
  resolve/matrix/io.cpp
  resolve/vector/Vector.cpp
  resolve/vector/Vector.hpp
  tests/unit/matrix/CMakeLists.txt
  tests/unit/matrix/MatrixFactorizationTests.hpp
  tests/unit/matrix/MatrixIoTests.hpp
  tests/unit/matrix/runMatrixFactorizationTests.cpp
  tests/unit/matrix/runMatrixIoTests.cpp
Labels: enhancement

#142 Let classical Gram-Schmidt fail expectedly
  tests/unit/TestBase.hpp
  tests/unit/vector/GramSchmidtTests.hpp
Labels: testing

#144 Cgs1 fixed failing tests
  resolve/vector/VectorHandlerCpu.cpp
Labels: bug

#140 Preliminary command-line options parser
  resolve/CMakeLists.txt
  resolve/LinSolverIterativeRandFGMRES.cpp
  resolve/LinSolverIterativeRandFGMRES.hpp
  resolve/SystemSolver.cpp
  resolve/SystemSolver.hpp
  resolve/utilities/CMakeLists.txt
  resolve/utilities/params/CMakeLists.txt
  resolve/utilities/params/CliOptions.cpp
  resolve/utilities/params/CliOptions.hpp
  tests/functionality/CMakeLists.txt
  tests/functionality/testSysRandGMRES.cpp
Labels: enhancement, testing

#143 Base class direct solver should not delete L and U factors
  resolve/LinSolver.cpp
  resolve/LinSolver.hpp
  resolve/LinSolverDirectCpuILU0.cpp
  resolve/LinSolverDirectKLU.cpp
  resolve/LinSolverDirectKLU.hpp
  resolve/LinSolverDirectSerialILU0.cpp
  resolve/LinSolverDirectSerialILU0.hpp
  resolve/matrix/MatrixHandlerImpl.hpp
  tests/unit/TestBase.hpp
Labels: bug
