Repository ORNL/ReSolve, pull requests merged in 2024-09, with the labels that each got.

#178 lusol factor extraction
  resolve/LinSolverDirectLUSOL.cpp
  resolve/LinSolverDirectLUSOL.hpp
  tests/unit/matrix/LUSOLTests.hpp
Labels: enhancement

#186 Update spack_cpu_build.yaml to not checkout in base image build step
  .github/workflows/spack_cpu_build.yaml
Labels: testing

#184 Refactor matrix file I/O
  README.md
  examples/r_KLU_GLU.cpp
  examples/r_KLU_GLU_matrix_values_update.cpp
  examples/r_KLU_KLU.cpp
  examples/r_KLU_KLU_standalone.cpp
  examples/r_KLU_cusolverrf_redo_factorization.cpp
  examples/r_KLU_rf.cpp
  examples/r_KLU_rf_FGMRES.cpp
  examples/r_KLU_rf_FGMRES_reuse_factorization.cpp
  examples/r_KLU_rocSolverRf_FGMRES.cpp
  examples/r_KLU_rocsolverrf.cpp
  examples/r_KLU_rocsolverrf_redo_factorization.cpp
  examples/r_SysSolver.cpp
  examples/r_SysSolverCuda.cpp
  examples/r_SysSolverHip.cpp
  examples/r_SysSolverHipRefine.cpp
  examples/r_randGMRES.cpp
  examples/r_randGMRES_CUDA.cpp
  examples/r_randGMRES_cpu.cpp
  resolve/LinSolverDirectCuSolverGLU.cpp
  resolve/LinSolverDirectCuSolverRf.cpp
  resolve/LinSolverDirectCuSparseILU0.cpp
  resolve/LinSolverDirectRocSolverRf.cpp
  resolve/LinSolverDirectRocSparseILU0.cpp
  resolve/LinSolverDirectSerialILU0.cpp
  resolve/matrix/CMakeLists.txt
  resolve/matrix/Coo.cpp
  resolve/matrix/Coo.hpp
  resolve/matrix/Csc.cpp
  resolve/matrix/Csc.hpp
  resolve/matrix/Csr.cpp
  resolve/matrix/Csr.hpp
  resolve/matrix/MatrixHandler.cpp
  resolve/matrix/MatrixHandler.hpp
  resolve/matrix/MatrixHandlerCuda.cpp
  resolve/matrix/MatrixHandlerHip.cpp
  resolve/matrix/Sparse.cpp
  resolve/matrix/Sparse.hpp
  resolve/matrix/Utilities.cpp
  resolve/matrix/Utilities.hpp
  resolve/matrix/io.cpp
  resolve/matrix/io.hpp
  tests/functionality/testKLU.cpp
  tests/functionality/testKLU_GLU.cpp
  tests/functionality/testKLU_Rf.cpp
  tests/functionality/testKLU_Rf_FGMRES.cpp
  tests/functionality/testKLU_RocSolver.cpp
  tests/functionality/testKLU_RocSolver_FGMRES.cpp
  tests/functionality/testSysGLU.cpp
  tests/functionality/testSysRandGMRES.cpp
  tests/functionality/testSysRefactor.cpp
  tests/functionality/testVersion.cpp
  tests/unit/matrix/MatrixIoTests.hpp
  tests/unit/matrix/runMatrixIoTests.cpp
Labels: bug, enhancement

#189 Add functionality test for LUSOL
  resolve/LinSolverDirectLUSOL.cpp
  tests/functionality/CMakeLists.txt
  tests/functionality/testLUSOL.cpp
  tests/unit/matrix/CMakeLists.txt
Labels: enhancement, testing

#190 Matrix handler now checks in the background if the matrix is CSR.
  examples/r_KLU_GLU.cpp
  examples/r_KLU_GLU_matrix_values_update.cpp
  examples/r_KLU_KLU.cpp
  examples/r_KLU_KLU_standalone.cpp
  examples/r_KLU_cusolverrf_redo_factorization.cpp
  examples/r_KLU_rf.cpp
  examples/r_KLU_rf_FGMRES.cpp
  examples/r_KLU_rf_FGMRES_reuse_factorization.cpp
  examples/r_KLU_rocSolverRf_FGMRES.cpp
  examples/r_KLU_rocsolverrf.cpp
  examples/r_KLU_rocsolverrf_redo_factorization.cpp
  examples/r_SysSolver.cpp
  resolve/LinSolverIterativeFGMRES.cpp
  resolve/LinSolverIterativeRandFGMRES.cpp
  resolve/SystemSolver.cpp
  resolve/matrix/Coo.cpp
  resolve/matrix/Csc.cpp
  resolve/matrix/Csr.cpp
  resolve/matrix/MatrixHandler.cpp
  resolve/matrix/MatrixHandler.hpp
  resolve/matrix/MatrixHandlerCpu.cpp
  resolve/matrix/MatrixHandlerCpu.hpp
  resolve/matrix/MatrixHandlerCuda.cpp
  resolve/matrix/MatrixHandlerCuda.hpp
  resolve/matrix/MatrixHandlerHip.cpp
  resolve/matrix/MatrixHandlerHip.hpp
  resolve/matrix/MatrixHandlerImpl.hpp
  resolve/matrix/Sparse.cpp
  resolve/matrix/Sparse.hpp
  tests/functionality/testKLU.cpp
  tests/functionality/testKLU_GLU.cpp
  tests/functionality/testKLU_Rf.cpp
  tests/functionality/testKLU_Rf_FGMRES.cpp
  tests/functionality/testKLU_RocSolver.cpp
  tests/functionality/testKLU_RocSolver_FGMRES.cpp
  tests/functionality/testLUSOL.cpp
  tests/functionality/testSysGLU.cpp
  tests/functionality/testSysRefactor.cpp
  tests/unit/matrix/MatrixHandlerTests.hpp
Labels: bug
