Repository ORNL/ReSolve, pull requests merged in 2024-06, with the labels that each got.

#153 add `LinSolverDirectLUSOL`, with initial support for solving Ax = rhs
  .editorconfig
  .gitignore
  CMakeLists.txt
  resolve/CMakeLists.txt
  resolve/Common.hpp
  resolve/LinSolverDirectLUSOL.cpp
  resolve/LinSolverDirectLUSOL.hpp
  resolve/LinSolverIterativeRandFGMRES.cpp
  resolve/lusol/CMakeLists.txt
  resolve/lusol/LICENSE.md
  resolve/lusol/lusol.f90
  resolve/lusol/lusol.hpp
  resolve/lusol/lusol_precision.f90
  resolve/matrix/CMakeLists.txt
  resolve/matrix/Coo.cpp
  resolve/matrix/Coo.hpp
  resolve/matrix/Csc.cpp
  resolve/matrix/Csc.hpp
  resolve/matrix/Csr.cpp
  resolve/matrix/Sparse.hpp
  resolve/random/RandomSketchingCountCpu.cpp
  resolve/random/RandomSketchingFWHTCpu.cpp
  resolve/utilities/logger/Logger.cpp
  resolve/utilities/logger/Logger.hpp
  resolve/vector/Vector.cpp
  tests/unit/matrix/CMakeLists.txt
  tests/unit/matrix/LUSOLTests.hpp
  tests/unit/matrix/runLUSOLTests.cpp
Labels: enhancement

#157 Fix flipped columns/rows in CSC matrix implementation.
  resolve/matrix/Csc.cpp
  resolve/matrix/Csc.hpp
Labels: bug

#172 Update spack_cpu_build.yaml to build ~klu+lusol
  .github/workflows/spack_cpu_build.yaml
Labels: testing, spack
