Repository ORNL/ReSolve, pull requests merged in 2025-06, with the labels that each got.

#307 Fix memory leaks
  examples/gluRefactor.cpp
  examples/gpuRefactor.cpp
  examples/kluFactor.cpp
  examples/kluRefactor.cpp
  examples/randGmres.cpp
  examples/sysRefactor.cpp
  resolve/GramSchmidt.cpp
  resolve/LinSolverIterativeFGMRES.cpp
  resolve/LinSolverIterativeRandFGMRES.cpp
  resolve/SystemSolver.cpp
  resolve/matrix/Csr.cpp
  resolve/utilities/params/CliOptions.cpp
  resolve/utilities/params/CliOptions.hpp
  tests/functionality/testKlu.cpp
  tests/functionality/testRefactor.cpp
  tests/functionality/testSysGmres.cpp
  tests/unit/matrix/MatrixHandlerTests.hpp
  tests/unit/matrix/MatrixIoTests.hpp
  tests/unit/matrix/SparseTests.hpp
  tests/unit/vector/VectorHandlerTests.hpp
  tests/unit/vector/VectorTests.hpp
Labels: bug, iterative solver

#305 Update redundant scaling kernel names
  resolve/LinSolverDirectCuSolverRf.cpp
  resolve/LinSolverDirectRocSolverRf.cpp
  resolve/cuda/CudaMemory.hpp
  resolve/cuda/cudaKernels.cu
  resolve/cuda/cudaKernels.h
  resolve/cuda/cudaVectorKernels.cu
  resolve/cuda/cudaVectorKernels.h
  resolve/hip/HipMemory.hpp
  resolve/hip/hipKernels.h
  resolve/hip/hipKernels.hip
  resolve/hip/hipVectorKernels.h
  resolve/hip/hipVectorKernels.hip
  resolve/matrix/MatrixHandler.cpp
  resolve/matrix/MatrixHandler.hpp
  resolve/matrix/MatrixHandlerCpu.cpp
  resolve/matrix/MatrixHandlerCpu.hpp
  resolve/matrix/MatrixHandlerCuda.cpp
  resolve/matrix/MatrixHandlerCuda.hpp
  resolve/matrix/MatrixHandlerHip.cpp
  resolve/matrix/MatrixHandlerHip.hpp
  resolve/matrix/MatrixHandlerImpl.hpp
  resolve/vector/VectorHandler.cpp
  resolve/vector/VectorHandler.hpp
  resolve/vector/VectorHandlerCpu.cpp
  resolve/vector/VectorHandlerCpu.hpp
  resolve/vector/VectorHandlerCuda.cpp
  resolve/vector/VectorHandlerCuda.hpp
  resolve/vector/VectorHandlerHip.cpp
  resolve/vector/VectorHandlerHip.hpp
  resolve/vector/VectorHandlerImpl.hpp
  tests/unit/matrix/MatrixHandlerTests.hpp
  tests/unit/matrix/runMatrixHandlerTests.cpp
  tests/unit/vector/VectorHandlerTests.hpp
  tests/unit/vector/runVectorHandlerTests.cpp
Labels: enhancement

#325 Add warnings flags
  CMakeLists.txt
  tests/unit/vector/VectorHandlerTests.hpp
Labels: compiler warnings
